/**
 * Panel ürün dili — sabit metinler (i18n altyapısı olmadan tek dil).
 * Listelerde tekrarlayan boş/hint metinleri buradan kullanın.
 */
export const PANEL_COPY = {
    listEmptyMessage: 'Kayıt bulunamadı.',
    listEmptyHint: 'Arama veya filtreleri değiştirerek tekrar deneyin.',
    /** `settings/clinics` — API scope’a göre liste boş olabilir */
    clinicsListEmptyMessage: 'Görüntüleme yetkiniz olan klinik bulunmuyor.',
    clinicsListEmptyHint: 'Atama veya ek yetki için kurum yöneticinize başvurun.',
    loadingDefault: 'Yükleniyor…',
    filterPlaceholderAll: 'Tümü',
    buttonSearch: 'Ara',
    buttonClear: 'Temizle',
    buttonSave: 'Kaydet',
    buttonCancel: 'İptal',
    buttonDetail: 'Detay',
    buttonRefresh: 'Yenile',
    labelClient: 'Müşteri',
    labelPet: 'Hayvan',
    /** Dashboard — klinik bağlamı yokken */
    dashboardNeedClinicMessage: 'Önce bir klinik seçmelisiniz.',
    dashboardNeedClinicHint:
        'Özet, randevu, finans ve listeler seçili klinik üzerinden yüklenir. Devam etmek için bir klinik seçin.',
    dashboardQuickActionsTitle: 'Hızlı işlemler',
    dashboardContextFootnote: 'Veriler seçili klinik bağlamındadır; bugünkü randevular yerel güne göredir.',
    cancelledAppointmentExamCreateBlocked: 'İptal edilmiş randevu için muayene oluşturulamaz.',
    cancelledAppointmentExamCreateHint: 'Bu işlem sadece aktif randevu akışlarında kullanılabilir.',
    /** Raporlar — panel */
    reportsNavGroup: 'Raporlar',
    reportsFilterDateFrom: 'Başlangıç tarihi',
    reportsFilterDateTo: 'Bitiş tarihi',
    reportsFilterClinic: 'Klinik',
    reportsFilterSearch: 'Arama',
    reportsClinicPanelDefault: 'Panel seçili klinik',
    reportsLoadingMessage: 'Rapor yükleniyor…',
    reportsLoadErrorFallback: 'Rapor verileri yüklenemedi.',
    reportsExportCsv: 'CSV indir',
    reportsExportXlsx: 'Excel indir',
    reportsExportResponseEmpty: 'İndirilecek dosya oluşturulamadı.',
    reportsExportFailedFallback: 'Dışa aktarma işlemi tamamlanamadı.',
    reportsTotalRecords: 'Toplam kayıt',
    reportsColClinic: 'Klinik',
    reportsColNotes: 'Not',
    reportsColPrimaryLocalTime: 'Zaman',
    paymentsReportTitle: 'Ödeme hareketleri',
    paymentsReportDescription: 'Tahsilat hareketlerini tarih, klinik ve ödeme yöntemine göre inceleyin.',
    paymentsReportDefaultPeriodHint:
        'Başlangıç ve bitiş tarihi seçmezseniz ayın başından bugüne kadar olan tahsilatlar gösterilir.',
    paymentsReportTotalAmount: 'Toplam tahsilat',
    paymentsReportColMethod: 'Ödeme yöntemi',
    paymentsReportSearchPlaceholder: 'Müşteri, hayvan, not veya para birimi ile ara…',
    paymentsReportEmptyMessage: 'Rapor kaydı bulunamadı.',
    paymentsReportEmptyHint: 'Seçili filtrelere uygun kayıt yok. Tarih aralığını veya diğer filtreleri değiştirip tekrar deneyin.',
    appointmentsReportTitle: 'Randevu hareketleri',
    appointmentsReportDescription: 'Randevuları tarih, durum ve klinik bilgisine göre takip edin.',
    appointmentsReportDefaultPeriodHint:
        'Başlangıç ve bitiş tarihi seçmezseniz ayın başından bugüne kadar olan randevular gösterilir. Klinik seçmezseniz panelde seçili klinik kullanılır.',
    appointmentsReportColStatus: 'Durum',
    appointmentsReportSearchPlaceholder: 'Not; müşteri, hayvan, tür veya ırk metni…',
    appointmentsReportEmptyMessage: 'Rapor kaydı bulunamadı.',
    appointmentsReportEmptyHint: 'Seçili filtrelere uygun kayıt yok. Tarih aralığını veya diğer filtreleri değiştirip tekrar deneyin.',
    examinationsReportTitle: 'Muayene raporu',
    examinationsReportDescription: 'Muayene kayıtlarını tarih, klinik ve arama kriterlerine göre görüntüleyin.',
    examinationsReportDefaultPeriodHint:
        'Başlangıç ve bitiş tarihi seçmezseniz ayın başından bugüne kadar olan muayeneler gösterilir. Klinik seçmezseniz panelde seçili klinik kullanılır.',
    examinationsReportColLinkedAppointment: 'Bağlı randevu',
    examinationsReportColVisitReason: 'Geliş nedeni',
    examinationsReportColAssessment: 'Değerlendirme',
    examinationsReportLinkedAppointment: 'Randevu detayı',
    examinationsReportNoAppointment: 'Bağlı değil',
    examinationsReportSearchPlaceholder: 'Sebep, bulgu, değerlendirme, not; müşteri, hayvan, tür veya ırk metni…',
    examinationsReportEmptyMessage: 'Rapor kaydı bulunamadı.',
    examinationsReportEmptyHint: 'Seçili filtrelere uygun kayıt yok. Tarih aralığını veya diğer filtreleri değiştirip tekrar deneyin.',
    vaccinationsReportTitle: 'Aşı raporu',
    vaccinationsReportDescription: 'Uygulanan ve planlanan aşı kayıtlarını tarih, durum ve klinik bilgisine göre takip edin.',
    vaccinationsReportDefaultPeriodHint:
        'Başlangıç ve bitiş tarihi seçmezseniz ayın başından bugüne kadar olan kayıtlar gösterilir. Klinik seçmezseniz panelde seçili klinik kullanılır. Planlanan aşılar plan tarihine, uygulanan aşılar uygulama tarihine göre raporlanır.',
    vaccinationsReportColVaccinationDate: 'Rapor tarihi',
    vaccinationsReportColVaccineName: 'Aşı adı',
    vaccinationsReportColStatus: 'Durum',
    vaccinationsReportColAppliedAt: 'Uygulama zamanı',
    vaccinationsReportColNextDue: 'Sonraki doz',
    vaccinationsReportSearchPlaceholder: 'Aşı adı, not; müşteri, hayvan, tür veya ırk metni…',
    vaccinationsReportEmptyMessage: 'Rapor kaydı bulunamadı.',
    vaccinationsReportEmptyHint: 'Seçili filtrelere uygun kayıt yok. Tarih aralığını veya diğer filtreleri değiştirip tekrar deneyin.',
    /** Kiracı — rol yetki matrisi (salt okunur) */
    tenantRoleMatrixNavTitle: 'Hesap',
    tenantRoleMatrixTitle: 'Rol Yetki Özeti',
    tenantRoleMatrixDescription:
        'Bu ekran salt okunur bir özet görünümüdür. Sunucuda tanımlı rol-yetki bağlarını gösterir; tenant panelinden düzenleme yapılamaz.',
    tenantRoleMatrixLoading: 'Rol Yetki Özeti yükleniyor…',
    tenantRoleMatrixLoadError: 'Rol Yetki Özeti yüklenemedi.',
    tenantRoleMatrixEmptyMessage: 'Bu rol için ayrı yetki bağı tanımlı değil.',
    tenantRoleMatrixEmptyHint: 'Bu ortamda rol yetki bağları tanımlı değil veya henüz uygulanmamış olabilir.',
    tenantRoleMatrixGlobalInfo:
        'Bu ekran yalnızca bilgilendirme amaçlıdır. Rol-yetki bağları merkezde tanımlanır ve tenant panelinden değiştirilemez.',
    tenantRoleMatrixTotalPrefix: 'Toplam',
    tenantRoleMatrixTotalSuffix: 'yetki',
    tenantRoleMatrixGroupOther: 'Diğer',
    tenantRoleMatrixColRole: 'Rol',
    tenantRoleMatrixColPermissions: 'Yetkiler',
    tenantRoleMatrixBackMembers: 'Üye listesine dön',
    /** Üye detayı — roller ve birleşik yetki özeti (salt okunur) */
    tenantMemberRolesSectionTitle: 'Roller ve yetki özeti',
    tenantMemberSummaryRolesPart: 'rol atanmış',
    tenantMemberSummaryUniquePermsPart: 'benzersiz yetki',
    tenantMemberSummaryGroupsPart: 'yetki grubu',
    tenantMemberViewPermissionSummaryButton: 'Yetki özetini görüntüle',
    tenantMemberMatrixForSummaryError:
        'Yetki özeti için rol matrisi yüklenemedi; özet sayıları eksik veya boş olabilir.',
    tenantMemberPermissionDialogTitle: 'Yetki Özeti',
    tenantMemberPermissionDialogHint:
        'Aşağıda bu kullanıcıya atanmış tüm rollerden gelen etkili yetkiler birleştirilmiş ve tekilleştirilmiş olarak gösterilir.',
    tenantMemberPermissionDialogAssignedRoles: 'Bu kullanıcıya atanmış roller',
    tenantMemberPermissionDialogGroupsTitle: 'Yetki grupları',
    tenantMemberPermissionDialogAccordionHint: 'Gruplar varsayılan kapalıdır; görmek istediğiniz grubu açın.',
    tenantMemberPermissionDialogEmpty:
        'Bu üyenin rolleri için tanımlı yetki bulunamadı veya matriste eşleşen satır yok.',
    tenantMemberSelfProfileHint:
        'Bu kayıt sizin hesabınıza ait. Rol ve klinik değişiklikleri bu ekrandan yapılamaz; başka bir yönetici ilgili işlemleri yapmalıdır.',
    /** Kurum daveti — `tenant-invite-status.utils` lifecycle etiketleri (ham status / enum sayısı yerine). */
    tenantInviteStatusPending: 'Bekliyor',
    tenantInviteStatusSent: 'Gönderildi',
    tenantInviteStatusAccepted: 'Kabul edildi',
    tenantInviteStatusAcceptedMembershipRemoved: 'Kabul edildi — Üyelikten çıkarıldı',
    tenantInviteStatusCancelled: 'İptal edildi',
    tenantInviteStatusExpired: 'Süresi doldu',
    tenantInviteStatusDeclined: 'Reddedildi',
    /** Backend `Revoked` (2) — panelde “iptal edilmiş davet” anlamıyla. */
    tenantInviteStatusRevoked: 'İptal edildi',
    tenantInviteStatusUnknown: 'Bilinmeyen durum'
} as const;
